name: "Terraform RDS Deployment"

on:
  push:
    paths:
      - "Vars/Dynamic_ec2.tfvars"
     

jobs:
  ec2_deployment:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "us-west-2"
      LOCK_TABLE_NAME: "terraform-lock"
      ROLE_TO_ASSUME: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.RoleName }}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials from GitHub Secrets
        run: |
          CREDS=$(aws sts assume-role --role-arn ${{ env.ROLE_TO_ASSUME }} --role-session-name "github-action-session" --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' --output text)
          read -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN <<< "$CREDS"
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> $GITHUB_ENV

      - name: Setup Terraform
        run: |
          curl -LO https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
          unzip terraform_1.0.11_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      - name: Terraform Init
        run: terraform init
        working-directory: ./

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -var-file=ec2.tfvars > plan_output.txt
          cat plan_output.txt
          if grep -q 'to destroy' plan_output.txt; then
            echo "Error: Resources to destroy detected. Failing the job."
            exit 1
          fi

      - name: Terraform Apply
        if: success()
        run: |
          terraform apply -auto-approve -var-file=ec2.tfvars
        working-directory: ./

      - name: Get DynamoDB Lock ID from Terraform State
        if: always()
        id: get_lock_id
        run: |
          BACKEND_STATE_FILE=".terraform/terraform.tfstate"
          if [ ! -f "$BACKEND_STATE_FILE" ]; then
            echo "Error: Backend state file not found at $BACKEND_STATE_FILE"
            exit 1
          fi
          # Using jq to parse the lock key
          KEY=$(jq -r '.backend.config.key' "$BACKEND_STATE_FILE")
          if [ -z "$KEY" ]; then
            echo "Error: Could not find 'key' in backend state file."
            exit 1
          fi
          LOCK_ID="terraform-lock/${KEY}-md5"
          echo "LOCK_ID is: $LOCK_ID"
          echo "LOCK_ID=${LOCK_ID}" >> $GITHUB_ENV

      - name: Delete Lock from DynamoDB
        if: always()
        run: |
          echo "Deleting lock ID from DynamoDB..."
          aws dynamodb delete-item --table-name "$LOCK_TABLE_NAME" \
            --key '{"LockID": {"S": "'"${LOCK_ID}"'"}}' \
            --region $AWS_REGION
          echo "Lock deleted successfully."
