name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      id: aws-creds
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::295257193777:role/GitHub
        aws-region: eu-west-1
        role-session-name: GitHubActionSession
        audience: sts.amazonaws.com
    - name: Verify AWS identity
      run: |
        aws sts get-caller-identity
    - name: Request OIDC Token
      run: |
        echo "Requesting OIDC token"
        curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" $ACTIONS_ID_TOKEN_REQUEST_URL


    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.1.0'  

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform/dynamic_ec2/modules/dynamic_ec2

    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -no-color -out=plan.txt
      working-directory: ./terraform/dynamic_ec2/modules/dynamic_ec2
      continue-on-error: true

    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #   run: |
    #     terraform apply -auto-approve
    #   working-directory: ./terraform/dynamic_ec2/modules/dynamic_ec2

    # - name: Terraform Format Check
    #   run: terraform fmt -check
    #   working-directory: ./terraform/dynamic_ec2/modules/dynamic_ec2

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform/dynamic_ec2/modules/dynamic_ec2

    - name: Upload Terraform Plan Output
      # if: always() && steps.plan.outcome == 'failure'
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan
        path: plan.txt

